apiVersion: apps/v1
kind: Deployment
metadata:
  name: dong-was
  namespace: dong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dong-was
  template:
    metadata:
      labels:
        app: dong-was
    spec:
      initContainers:
        - name: make-was-status
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache bash >/dev/null 2>&1 || true
              cp /scripts/make-status-page.sh /tmp/make-status-page.sh
              chmod +x /tmp/make-status-page.sh
              /tmp/make-status-page.sh || true
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: was-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: was-config
                  key: DB_PORT
          volumeMounts:
            - name: was-scripts
              mountPath: /scripts
            - name: was-root
              mountPath: /usr/local/tomcat/webapps/ROOT

      containers:
        - name: dong-was
<<<<<<< HEAD
          image: 401670234592.dkr.ecr.ap-northeast-2.amazonaws.com/dong/dongtest:(IMAGE_TAG)
=======
          image: 401670234592.dkr.ecr.ap-northeast-2.amazonaws.com/dong/dongtest:6f93a2a5fa55fc2bd6f395b0e388edb04c43cdbb
>>>>>>> 2c693a34c49932d0f745c0be9ab604d4dbcd2686
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: was-root
              mountPath: /usr/local/tomcat/webapps/ROOT

      volumes:
        - name: was-scripts
          configMap:
            name: was-config
            defaultMode: 0755
        - name: was-root
          emptyDir: {}