apiVersion: apps/v1
kind: Deployment
metadata:
  name: dong-was
  namespace: dong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dong-was
  template:
    metadata:
      labels:
        app: dong-was
    spec:
      initContainers:
        - name: make-dbcheck-page
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache busybox-extras >/dev/null 2>&1 || true
              DB_HOST="mysql"
              DB_PORT="3306"
              STATUS="FAIL"
              if nc -z -w 2 "${DB_HOST}" "${DB_PORT}"; then
                STATUS="OK"
              fi

              cat > /tomcat-root/index.html <<EOF
              <!DOCTYPE html>
              <html>
              <head><meta charset="UTF-8"><title>WAS</title></head>
              <body>
                <h1>WAS SERVER (Tomcat)</h1>
                <p>DB Connection (port check): <b>${STATUS}</b></p>
                <p>Target: ${DB_HOST}:${DB_PORT}</p>
              </body>
              </html>
              EOF
          volumeMounts:
            - name: was-root
              mountPath: /tomcat-root

      containers:
        - name: dong-was
<<<<<<< HEAD
          image: 401670234592.dkr.ecr.ap-northeast-2.amazonaws.com/dong/dongtest:latest
=======
          image: 401670234592.dkr.ecr.ap-northeast-2.amazonaws.com/dong/dongtest:de30b3c22e7b83140da693127af0a0d301268853
>>>>>>> cffc6e64b31949a6cb37adc14fa2435953a62bb6
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: was-root
              mountPath: /usr/local/tomcat/webapps/ROOT

      volumes:
        - name: was-root
          emptyDir: {}
